version: '3.8'
services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./server2/server.crt:/etc/ssl/certs/server.crt
      - ./server2/server.key:/etc/ssl/private/server.key
    depends_on:
      - server1
      - server2

  server1:
    build: ./server1
    expose:
      - "8081"
    volumes:
      - ./ui:/app/ui
  server2:
    build: ./server2
    expose:
      - "8082"
    volumes:
      - ./ui:/app/ui
    
      
